[project]
name = "hello"
version = "1.0.0"
description = "The basic blog app built in the Flask tutorial."
dependencies = [
    "flask", "python_jyutping", "json"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

